
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using NServiceBus;
using AmazonOrder.InternalMessages.Commands.Sales;
using AmazonOrder.Sales;


  namespace AmazonOrder.Web.Controllers
{
    public partial class TestMessagesController : Controller
    {
        //
        // GET: /TestMessages/

        public ActionResult Index()
        {
            return View();
        }

		
	    

        //
        // POST: /TestMessages/SendMessagePlaceOrder
          
        public IPlaceOrderSender PlaceOrderSender { get; set; }
          
        [HttpPost]
        public ActionResult SendMessagePlaceOrder(PlaceOrder PlaceOrder)
        {
            ConfigurePlaceOrder(PlaceOrder);
            PlaceOrderSender.Send(PlaceOrder);

            ViewBag.MessageSent = "PlaceOrder";

            return View("Index");
        }

		
        partial void ConfigurePlaceOrder(PlaceOrder message);
      
    }
}
