//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using NServiceBus;
using AmazonOrder.InternalMessages.Commands.Sales;


namespace AmazonOrder.Sales
{
    public partial class PlaceOrderSender : IPlaceOrderSender, ServiceMatrix.Shared.INServiceBusComponent
    {
		
        public void Send(PlaceOrder message)
        {
            ConfigurePlaceOrder(message);
            Bus.Send(message);
        }

        partial void ConfigurePlaceOrder(PlaceOrder message);

        public IBus Bus { get; set; }

    }
    
    public partial interface IPlaceOrderSender
    {
		
        void Send(PlaceOrder message);

    }
}
