//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using NServiceBus;
using AmazonOrder.InternalMessages.Commands.Sales;


namespace AmazonOrder.Sales
{
    public partial class PlaceOrderProcessor : IPlaceOrderProcessor, ServiceMatrix.Shared.INServiceBusComponent, IHandleMessages<PlaceOrder>
    {
		
		public void Handle(PlaceOrder message)
		{
			// Handle message on partial class
			this.HandleImplementation(message);

			// Auto-publish Event OrderAccepted
			var OrderAccepted = new AmazonOrder.Contracts.Sales.OrderAccepted();
			ConfigureOrderAccepted(message, OrderAccepted);
			this.Bus.Publish(OrderAccepted);
		}

		partial void HandleImplementation(PlaceOrder message);

		partial void ConfigureOrderAccepted(PlaceOrder incomingMessage, AmazonOrder.Contracts.Sales.OrderAccepted message);

        public IBus Bus { get; set; }

    }
    
    public partial interface IPlaceOrderProcessor
    {
		
    }
}
